server:
  port: 8092
management:
  endpoint:
    health:
      enabled: true
  server:
    port: 8098
spring:
    data:
      mongodb:
       host: localhost
       port: 27017
       database: BenchMark 
    jpa:
        show-sql: true
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.Query: DEBUG